### ISSUE TITLE
Setting GitHub Enterprise URL

### ISSUE THREAD

**Issue by Snugug** [flynn/flynn#2447]
I'd like to point the Flynn install I have at a GitHub Enterprise URL instead of GitHub Public but don't see a way to easily do that How can I point the token auth to GitHub Enterprise?

**Comment by titanous** [comment]
Currently not possible, but @jvatic can look into when he gets back.

**Comment by Snugug** [comment]
Great, thanks

**Comment by jvatic** [comment]
It [appears](https://developer.github.com/v3/enterprise/) this should be very easy to implement (just a matter of configuring a different API URL).

@Snugug is there an equivalent to [this link](https://github.com/settings/tokens/new?scopes=repo%2Cread%3Aorg%2Cread%3Apublic_key&description=Flynn%20Dashboard) given a GitHub Enterprise URL?

**Comment by Snugug** [comment]
Yah. Pretty much all GitHub Enterprise URL endpoints are `<host>` instead of `github.com`, that one included. The API URL is a little different though, moving to `<host>/api/v3`:
https://developer.github.com/v3/enterprise/

**Comment by jvatic** [comment]
@Snugug as of the next release you can set GITHUB_ENTERPRISE_HOST=\<host\> on the dashboard app to test things out (https://dashboard.CLUSTER_DOMAIN/apps/dashboard/env?system=true or via the cli, you'll need to reload the page for the config to take effect).

**Comment by Snugug** [comment]
Awesome, thanks!

**Comment by jvatic** [comment]
@Snugug Have you had a chance to try this out?

**Comment by Snugug** [comment]
Not yet. Probably won't get a chance to until the second week of March, but will check then and let you know

**Comment by titanous** [comment]
@Snugug Any chance you can test this out?

**Comment by Snugug** [comment]
I'm very sorry for the delay in testing this out. I know how frustrating it can be as an OSS maintainer to have an open fixed issue waiting on a response.

So it appears as if this _mostly_ works. The host setup works as expected (even though the dashboard seems to hang on saving), and it pulls the information correctly from my GitHub Enterprise install, but trying to launch any project produces the following error:

```
Cloning into '/tmp/app'...
fatal: could not read Username for '{{GITHUB_ENTERPRISE_HOST}}': No such device or address
exit status 128
```

`{{GITHUB_ENTERPRISE_HOST}}` is the value I entered

**Comment by jvatic** [comment]
@Snugug This error appears to be coming from the `git clone` command. Are you able to inspect the request to `POST /apps/taffy/jobs` via the network inspector and verify that the second item in `cmd` is a working clone URL?

**Comment by Snugug** [comment]
So, I tried to make sure I had a clean install by going through the upgrade process and https://github.com/flynn/flynn/issues/2619 happened, so now I'm stuck there. :cry: 

Once that's resolved I can try again with a clean install.

**Comment by Snugug** [comment]
Okay, #2619 is fixed, trying this again. Will report back

**Comment by jvatic** [comment]
@Snugug Have you had time to test this out again?

**Comment by Snugug** [comment]
When I tried it visually appeared to stall here:
```
===> 04:55:16.107 *** WARNING ***
===> 04:55:16.110 About to stop Flynn and remove all existing data
===> 04:55:16.113 Are you sure this is what you want?
(yes/no): yes
===> 04:55:18.920 stopping flynn-host daemon
===> 04:55:18.928 running "stop flynn-host"
flynn-host stop/waiting
===> 04:55:23.946 killing old containers
===> 04:55:24.006 destroying ZFS volumes
===> 04:55:24.013 running "flynn-host destroy-volumes --include-data"
opening volume state db...
DBUG[03-31|04:55:24] zfs get all -Hp flynn-default            package=zfs
```

I'm trying to re-run it again today from w/in my network, still visually stalled, hopefully it's just a visual thing though

**Comment by Snugug** [comment]
After 15 minutes paused there, I needed to kill my SSH connection to stop it. Going to try again

**Comment by Snugug** [comment]
Currently blocked on https://github.com/flynn/flynn/issues/2646

**Comment by Snugug** [comment]
(sorry this process is being so difficult!)

**Comment by Snugug** [comment]
@jvatic Yes, the second item in `cmd` is the correct HTTPS Git Cloe URL for that repo

**Comment by jvatic** [comment]
@Snugug Is it a private repo? If so, is there an auth token included in the URL? And does `git clone` work with it in a context absent from authorized ssh keys?

**Comment by Snugug** [comment]
* It is not a private repo
* No auth token is included in the URL
* Authentication is required when cloning from GHE, so either an SSH key needs to be in place, or an auth token is required when cloning with HTTPS. I assumed it would be constructed with one for the actual `git clone` but if not, then that's most likely the issue

**Comment by jvatic** [comment]
Okay, then the dashboard needs to treat all repos as private when dealing with GHE so the token gets included.

**Comment by Snugug** [comment]
Sounds like that's fair.

**Comment by jvatic** [comment]
@Snugug This should be fixed in the next release.

**Comment by Snugug** [comment]
Great, thanks! I'll take a look when it's released

**Comment by Snugug** [comment]
@jvatic I just ran the upgrade process for Flynn and tried this again, same error, and the API token doesn't appear in the clone URL. I'm expecting something like `https://{{token}}@github.company.com/user/repo.git` but it's still missing the token. Has your updated landed yet? I saw a few more [releases](https://github.com/flynn/flynn/releases) since we talked, so thought it may have been released

**Comment by jvatic** [comment]
@Snugug Can you run  `__modules['dashboard/config.js'].default.github_clone_auth_required` in the JavaScript console? It should output `true`.

**Comment by Snugug** [comment]
It's `undefined` (not in the object)

Is there a way to check the version of Flynn I'm running to ensure I"m on the latest?

**Comment by jvatic** [comment]
It sounds like this isn't in the release you're running.

You can SSH into the cluster and run `flynn-host version`.

**Comment by Snugug** [comment]
Has `https://dl.flynn.io/install-flynn` been updated to the latest release in GHE?

**Comment by titanous** [comment]
Looks like this change is in the nightly release, set `FLYNN_UPDATE_CHANNEL=nightly` while running the script.

**Comment by Snugug** [comment]
👍 All cloning seems to be working now from GHE repos! Thanks very much for all of the help and time!
