### ISSUE TITLE
Garbage Collection

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#2750]
We need a garbage collector to automatically remove the following potentially stale items:
- Releases + Slugs (these can currently be removed manually with `flynn release delete <id>`)
- Volumes
- Jobs (these remain in `flynn-host` indefinitely and are retrieved every 30s by the scheduler in SyncJobs)

One approach for releases is to only keep the most recent N versions, but as @philiplb mentioned in #1569:

> Keeping the N last versions might be troublesome in situations were you deploy N times in a row (shit happens). Now you can't rollback to the version from yesterday.
> 
> Proposal: Keep the last N versions and delete the other versions only if they reach a certain, configurable minimum age.

Once we merge #2744, we should have a cron-like component that makes periodic job requests to do things like this.

**Comment by lmars** [comment]
FYI not cleaning up old jobs lead to a scheduler bug: #3110.

The bug is fixed, but it does seem like wasted effort to be getting the status of thousands of stopped jobs every 30s, especially if they are already marked as stopped in the controller.

**Comment by lmars** [comment]
A large number of stopped jobs (e.g. 10,000) leads to quite high average bandwidth between hosts as each scheduler fetches ~10MB of jobs from each host every 30s, leading to about 6mbps average.

We should at the very least have a `flynn-host` command to just delete old jobs from the local state database.

**Comment by mhlz** [comment]
Is there any progress on the command to delete old jobs? We have an app that failed to start over a day or so in our development environment which makes the online log view impossible to open (browser hangs and sometimes outright crashes). It's not a big deal since we can still see the logs with `flynn log` but it'd be nice to get this fixed at some point.

**Comment by lmars** [comment]
@mhlz we updated the scheduler to only sync active jobs in #3767 (which prevents a large number of stopped jobs slowing the scheduler down) so removing old jobs is now less of a priority (it is beneficial to keep jobs in the host to help with fixing broken clusters by resurrecting old jobs).

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
