### ISSUE TITLE
in-place update made docker-receive unhealthy

### ISSUE THREAD

**Issue by hadifarnoud** [flynn/flynn#3242]
I tried an in-place update recently and that made Flynn unable to receive git pushes.
https://gist.github.com/hadifarnoud/d7ce6ad5d57a8729ac9d3b291c157455

I tried to kill docker-receive in an effort to respawn it. that didn't work and slowly other processes failed. I could not get a backup anymore, nor could I restore from a backup.
```
flynn-host bootstrap --from-backup flynn-backup-2016-07-15_192009.tar
14:51:18.885368 check online-hosts
14:53:19.026726 check online-hosts error: timed out waiting for 1 hosts to come online (currently 0 online)

The following hosts were discovered but remained unreachable:

http://127.0.0.1:1113
```

logs show this:
```
t=2016-08-07T08:59:36-0400 lvl=eror msg="error restoring state" app=host pid=11024 fn=runDaemon host.id=flynn1 err="could not restore from host persistence db: error loading container state: open /var/lib/flynn/container/state.json: no such file or directory"
```
I couldn't find `state.json` in fresh flynn install. can I still fix it?

I tried a reboot, Flynn does not boot up. 
version: `v20160721.2`

debug logs are quite big, I can upload part of them as collection was saved as tar.gz in /tmp folder.

is there anyway I can get a manual backup and clean install? my latest backup is a month old unfortunately.

**Comment by titanous** [comment]
You can use the faildump tool documented [in this gist](https://gist.github.com/titanous/36754c1da91c632640a7). If you just want database dumps, no compilation is required, you can connect to the database and dump manually.

**Comment by hadifarnoud** [comment]
It didn't work for me. `faildump` is complaining about missing `relations` and `columns`.
https://gist.github.com/hadifarnoud/16bae244dde5232f9a9dc4ce6ea0fecd

I chose biggest ZFS volume and mounted it. is it possible that I picked a wrong one?

**Comment by hadifarnoud** [comment]
I think I know what the issue is. We did S3 migration for blobstore. could this be the issue?

**Comment by titanous** [comment]
Please connect to the `542de2cab011a19e4bd1de4176b3cb45` database with `psql` and run `\dt` and gist the output here.

**Comment by hadifarnoud** [comment]
sorry I clean installed flynn from an old backup. got a snapshot on digitalocean. will spin up another node for debug asap.

<img width="534" alt="screen shot 1395-05-19 at 12 58 59 pm" src="https://cloud.githubusercontent.com/assets/589808/17519530/8c5cf5ec-5e61-11e6-8694-24b8fe26ae90.png">

**Comment by titanous** [comment]
Those errors don't make any sense. Are you still getting them?

**Comment by hadifarnoud** [comment]
yeah, I restored flynn from an old backup though. 

some tables were empty when I checked. I thought that might be due to S3 migration? I'm restoring from last snapshot to debug (will give you output of that database soon). can't push to flynn atm. git push gives me these errors:

```
hadifarnoud@MacBook-Pro shop-api (master)$ git push flynn master
Counting objects: 552, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (469/469), done.
Writing objects: 100% (552/552), 70.34 KiB | 0 bytes/s, done.
Total 552 (delta 368), reused 111 (delta 71)
-----> Building kamva-api...
-----> PHP app detected
-----> Bootstrapping...
remote:
remote: gzip: stdin: not in gzip format
remote: tar: Child returned status 1
remote: tar: Error is not recoverable: exiting now
remote: ERROR: Build failed: exec: job exited with status 2
To https://git.eg55.flynnhub.com/kamva-api.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.eg55.flynnhub.com/kamva-api.git'
```

**Comment by titanous** [comment]
The S3 migration shouldn't have anything to do with this.

I believe that error is actually an upstream issue in the PHP buildpack, please try:

```text
flynn env set BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-php
```

And deploy again.

**Comment by hadifarnoud** [comment]
can't set env
```
hadifarnoud@MacBook-Pro shop-api (master)$ flynn env set BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-php
web process type failed to start, got down job event
hadifarnoud@MacBook-Pro shop-api (master)$ flynn env set BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-php
deployer: worker job failed to start: unexpected HTTP status code: 404 Not Found
hadifarnoud@MacBook-Pro shop-api (master)$ flynn env set BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-php
deployer: worker job failed to start: unexpected HTTP status code: 404 Not Found
```

I meant [these errors](https://gist.github.com/hadifarnoud/16bae244dde5232f9a9dc4ce6ea0fecd) might be related to S3. I can't think of any other reason `faildump` doesn't work

**Comment by titanous** [comment]
Please run `sudo flynn-host collect-debug-info` on the cluster that is throwing those 404s.

I am unclear on why faildump isn't working, but I don't think it's worth debugging further, is there specific data you want? It should be pretty easy to get a database dump or the values of env vars etc.

**Comment by hadifarnoud** [comment]
https://gist.github.com/30c6cb25d8968129d5dbde90a2de3b09

the reason I want it is our apps. some where tricky to get to work. more importantly though, I need content of redis db, routes (domains that were set on one of the apps).

other than that, I can get over it 😃

**Comment by titanous** [comment]
The Redis data is gone. As [noted in our documentation](https://flynn.io/docs/databases/redis):

> The data stored in this process is ephemeral and is intended for caching and development use.

And:

> No safety or availability guarantees are currently provided for the Redis appliance. Data loss and inconsistency is likely. Any data stored should be treated as ephemeral and only used for caching, development, and testing.

You can get the name of the router database from the controller db with:

```text
select env->>'PGDATABASE' from resources join app_resources using (resource_id) join apps using (app_id) where apps.name = 'router';
```

After you connect to it, the information you are looking for should be in the `http_routes` table.

If you want any other specific data, or have trouble finding what you are looking for let me know specifically what you want and I can help you find it.

**Comment by titanous** [comment]
I believe the 404s are from the blobstore, try making a new app and deploying to it with the `BUILDPACK_URL` env var set.

**Comment by hadifarnoud** [comment]
thanks 🙏 . redis is not that important to us. created another app and everything worked.

**Comment by hadifarnoud** [comment]
it happened again. docker-receive is unhealthy. 

one strange thing that happened is one of my apps (I deleted the app and created this one after restore) have Redis but it can't connect to it. I created another app and that one works fine. 

deleting and re-adding Redis did not help. I created another app and tried `flynn redis redis-cli` but that didn't work either.

Redis instance log: https://gist.github.com/hadifarnoud/606abe83262f3d8892bece0f6fdc1d4c
debug logs: https://gist.github.com/657c2697d67e59de58e813a44f563520

**Comment by titanous** [comment]
@lmars I believe the Redis issue might be a duplicate of #3250

**Comment by lmars** [comment]
@hadifarnoud I have just merged #3247 which fixes the Redis issues.

In the meantime, you can run the commands I posted [here](https://github.com/flynn/flynn/issues/3250#issuecomment-238701568) to update the Redis image URI (or [this](https://github.com/flynn/flynn/issues/3250#issuecomment-238907685) if you get a `duplicate key` error).

**Comment by hadifarnoud** [comment]
I tried both methods and still Redis is not working.
```
hadifarnoud@MacBook-Pro shopbuilder (master)$ flynn -a redis-749bfb85-3c89-4716-867b-ae11a959a35b scale redis=1
scaling redis: 0=>1

18:29:42.050 ==> redis 7ccf6f88-eff6-4f07-8533-a97e262aa2f5 pending
18:29:42.341 ==> redis flynn1-7ccf6f88-eff6-4f07-8533-a97e262aa2f5 starting
18:29:44.556 ==> redis flynn1-7ccf6f88-eff6-4f07-8533-a97e262aa2f5 down
18:29:44.583 ==> redis ffcab171-1243-4326-8ef0-602521b66036 pending
18:29:44.715 ==> redis flynn1-ffcab171-1243-4326-8ef0-602521b66036 starting
18:29:45.520 ==> redis flynn1-ffcab171-1243-4326-8ef0-602521b66036 down
18:29:45.520 ==> redis 8863e063-519b-4216-9d26-85106f142bc6 pending
Timed out waiting for job events. Waited 20 seconds.
expected: map[redis:map[up:1]]
actual: map[redis:map[pending:3 starting:2 down:2]]
```

now `REDIS_IMAGE_URI=$(grep -oP 'https://dl.flynn.io/tuf\?name=flynn/redis&id=\w+' /etc/flynn/bootstrap-manifest.json | uniq)` is return nothing when run on flynn box

**Comment by hadifarnoud** [comment]
/etc/flynn/bootstrap-manifest.json:
```
root@flynn1:~# cat /etc/flynn/bootstrap-manifest.json | grep redis
    "id": "redis",
      "name": "redis",
        "FLYNN_REDIS": "redis",
        "REDIS_IMAGE_URI": "https://dl.flynn.io/tuf?name=flynn/redis&id=dcd0fff8a5cd156f76db5af4b5caa40e86261a0d8af0df7baf88868037beab1b"
      "uri": "https://dl.flynn.io/tuf?name=flynn/redis&id=dcd0fff8a5cd156f76db5af4b5caa40e86261a0d8af0df7baf88868037beab1b"
    "id": "add-redis-provider",
    "name":"redis",
    "url":"http://redis-api.discoverd/clusters"
    "id": "redis-wait",
    "url": "http://redis-api.discoverd/ping"
```

**Comment by lmars** [comment]
@hadifarnoud 

> I tried both methods and still Redis is not working.

Did you get an error? Can you gist the full output of running both commands?

> REDIS_IMAGE_URI=$(grep -oP 'https://dl.flynn.io/tuf\?name=flynn/redis&id=\w+' /etc/flynn/bootstrap-manifest.json | uniq) is return nothing when run on flynn box

This command is not supposed to do anything, it just populates the `REDIS_IMAGE_URI` variable with the appropriate URI from the bootstrap manifest. Running `echo $REDIS_IMAGE_URI` should show you the value of the variable, but it may be easier just to set it manually:

```
$ REDIS_IMAGE_URI="https://dl.flynn.io/tuf?name=flynn/redis&id=dcd0fff8a5cd156f76db5af4b5caa40e86261a0d8af0df7baf88868037beab1b"
```

This variable is then used to fix the database records in the commands I posted.

**Comment by hadifarnoud** [comment]
so that grep command should be run on flynn host then. I tried getting artifact id with
```
$ flynn -a controller pg psql -- -c "SELECT artifact_id FROM artifacts WHERE uri = 'https://dl.flynn.io/tuf?name=flynn/redis&id=57b74ddacab85a36f263957ae042bddbae8a8432631cf023029aed52ca109d7e'"
```

and set artifact id like you explained in [here](https://github.com/flynn/flynn/issues/3250#issuecomment-239042667)

I did not get any error other than these when scaling up redis again:
```
scaling redis: 0=>1

19:55:45.129 ==> redis 41206c21-d624-46da-b823-2e4bbfcd6424 pending
19:55:45.330 ==> redis flynn1-41206c21-d624-46da-b823-2e4bbfcd6424 starting
19:55:46.855 ==> redis flynn1-41206c21-d624-46da-b823-2e4bbfcd6424 down
19:55:46.855 ==> redis b4953df1-c2e8-4bf7-ad45-2de0a9f909f6 pending
19:55:46.931 ==> redis flynn1-b4953df1-c2e8-4bf7-ad45-2de0a9f909f6 starting
19:55:48.083 ==> redis flynn1-b4953df1-c2e8-4bf7-ad45-2de0a9f909f6 down
19:55:48.083 ==> redis 50ffdedb-99d8-40ed-b20d-7cfed4909990 pending
Timed out waiting for job events. Waited 20 seconds.
expected: map[redis:map[up:1]]
actual: map[redis:map[down:2 pending:3 starting:2]]
hadifarnoud@MacBook-Pro ~ $ flynn -a kamva-api redis redis-cli
Could not connect to Redis at redis-749bfb85-3c89-4716-867b-ae11a959a35b.discoverd:6379: Name or service not known
```

and still can't connect to redis-cli
```
hadifarnoud@MacBook-Pro ~ $ flynn -a kamva-api redis redis-cli
Could not connect to Redis at redis-749bfb85-3c89-4716-867b-ae11a959a35b.discoverd:6379: Name or service not known
not connected>
```

**Comment by lmars** [comment]
@hadifarnoud from our discussion in IRC, the Redis app was still failing to start because the scheduler had the old artifact cached in memory (artifacts are supposed to be immutable so that is correct behaviour).

To get around this, we tried to set an env var on the Redis app (`flynn -a redis-xxx env set FOO=BAR`) thus creating a new release, and Redis did start up correctly but the deploy failed because your controller DB does not include [this fix](https://github.com/flynn/flynn/commit/ceefb2cf465b665024782914e958d458451e4e37) (i.e. the service name for the Redis release is `redis` when it should be the app name like `redis-xxx`).

We tried to apply the fix manually by starting a postgres shell with `flynn -a controller pg psql` and pasting in [the migration SQL](https://github.com/flynn/flynn/blob/v20160813.0/controller/schema.go#L395-L403) but that failed because it uses `jsonb_set` which is only available in pg 9.5, and you are still on pg 9.4.

I unfortunately need to head offline and won't be back for a couple of days but the next step would be to either come up with a pg 9.4 compatible equivalent of that SQL and then attempt `flynn -a redis-xxx env set FOO=BAR` again, or to manually update the Redis release with:

* `flynn -a redis-xxx release show --json > release.json`
* change `"service": "redis"` to `"service": "redis-xxx"` in the resulting `release.json`
* update the release with `flynn release update release.json`

**Comment by hadifarnoud** [comment]
I wasn't able to `flynn release update release.json`
```
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/flynn/flynn/pkg/shutdown.(*handler).exit(0xc208091980, 0x0, 0x0, 0x0, 0x6cef00, 0xc20810f8d0)
	/tmp/tmp.MWbJMA6H4B/src/github.com/flynn/flynn/pkg/shutdown/handler.go:69 +0x12e
github.com/flynn/flynn/pkg/shutdown.Exit()
	/tmp/tmp.MWbJMA6H4B/src/github.com/flynn/flynn/pkg/shutdown/handler.go:40 +0x73
main.runReleaseUpdate(0xc2080f4ee0, 0x17b25d8, 0xc208036d50, 0x0, 0x0)
	/tmp/tmp.MWbJMA6H4B/src/github.com/flynn/flynn/cli/release.go:254 +0x703
main.runRelease(0xc2080f4ee0, 0x17b25d8, 0xc208036d50, 0x0, 0x0)
	/tmp/tmp.MWbJMA6H4B/src/github.com/flynn/flynn/cli/release.go:121 +0x406
main.runCommand(0x7fff5fbff836, 0x7, 0xc2080cf8c0, 0x2, 0x2, 0x0, 0x0)
	/tmp/tmp.MWbJMA6H4B/src/github.com/flynn/flynn/cli/main.go:174 +0x7c7
main.main()
	/tmp/tmp.MWbJMA6H4B/src/github.com/flynn/flynn/cli/main.go:126 +0xd1a

goroutine 5 [syscall]:
os/signal.loop()
	/tmp/tmp.MWbJMA6H4B/src/github.com/flynn/flynn/util/_toolchain/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/tmp/tmp.MWbJMA6H4B/src/github.com/flynn/flynn/util/_toolchain/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [chan receive]:
github.com/flynn/flynn/pkg/shutdown.(*handler).wait(0xc208091980)
	/tmp/tmp.MWbJMA6H4B/src/github.com/flynn/flynn/pkg/shutdown/handler.go:58 +0x158
created by github.com/flynn/flynn/pkg/shutdown.newHandler
	/tmp/tmp.MWbJMA6H4B/src/github.com/flynn/flynn/pkg/shutdown/handler.go:25 +0xa8

goroutine 20 [select]:
net/http.(*persistConn).writeLoop(0xc20807a630)
	/tmp/tmp.MWbJMA6H4B/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/tmp/tmp.MWbJMA6H4B/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/transport.go:661 +0xcbc

goroutine 19 [runnable]:
net/http.(*persistConn).readLoop(0xc20807a630)
	/tmp/tmp.MWbJMA6H4B/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/tmp/tmp.MWbJMA6H4B/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/transport.go:660 +0xc9f

goroutine 17 [sleep]:
net.func·019()
	/tmp/tmp.MWbJMA6H4B/src/github.com/flynn/flynn/util/_toolchain/go/src/net/dnsclient_unix.go:240 +0x5a
created by net.loadConfig
	/tmp/tmp.MWbJMA6H4B/src/github.com/flynn/flynn/util/_toolchain/go/src/net/dnsclient_unix.go:269 +0x20c
```

**Comment by lmars** [comment]
@hadifarnoud sorry, I made a typo, it should be:

```
$ flynn -a redis-xxx release update release.json
```

**Comment by hadifarnoud** [comment]
thanks @lmars. it worked!
